services:
  pwb-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: pwb-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /Users/robzeeman/Documents/DI_code/partikelwoordenboek/index:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - robz

  raa-app:
    image: registry.diginfra.net/tsd/partikelwb:0.9
    ports:
      - 80:5000
    environment:
      ES_URI: pwb-elastic
      ES_PORT: 9200
    networks:
      - robz

networks:
  robz:
    external: false

