version: '2'

services:
  pwb-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: pwb-elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /data/products/partikels/index:/usr/share/elasticsearch/data
      - /home/robz:/home
    networks:
      - traefik-public


  pwb-app:
    image: registry.diginfra.net/tsd/partikelwb:0.9
    container_name: pwb-app
    restart: unless-stopped
    environment:
      ES_URI: pwb-elastic
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pwb-app.loadbalancer.server.port=5000"
      - "traefik.http.routers.pwb-app.entrypoints=http"
      - "traefik.http.routers.pwb-app.rule=Host(`pwb.sd.di.huc.knaw.nl`)"
    expose:
      - 5000
    networks:
      - traefik-public


networks:
  traefik-public:
    external: true






